services:
  db:
    image: postgres:13-alpine
    container_name: hashing_db
    env_file:
      - ./development.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: hashing_backend
    env_file:
      - ./development.env
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: hashing_frontend
    env_file:
      - ./development.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 